FROM %(parent_image_id)s

MAINTAINER Masami Yonehara

ENV PATH $PATH:/usr/ruby/bin

RUN git clone https://github.com/hdemon/yukkuri-ranking-aggregator.git
RUN cd yukkuri-ranking-aggregator && bundle install -j4
RUN echo "10 17 * * * /bin/bash -l -c 'cd /yukkuri-ranking-aggregator && bundle exec rake crawl:daily >> /var/log/cron_log.log 2>&1'" >> /etc/cron.d/crawler
