FROM ubuntu

MAINTAINER Masami Yonehara

ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/ruby/bin

RUN apt-get update -y
# see https://github.com/dotcloud/docker/issues/1724
RUN apt-mark hold initscripts
RUN apt-get upgrade -y

RUN apt-get install -y \
  sudo \
  man-db \
  wget \
  git \
  nano \
  curl \
  cron \
  net-tools \
  patch \
  gcc \
  g++ \
  openssl \
  make \
  bzip2 \
  autoconf \
  automake \
  libtool \
  bison \
  build-essential \
  mysql-client \
  libmysqlclient-dev \
  libreadline6 \
  libreadline-dev \
  zlib1g \
  zlib1g-dev \
  libssl-dev \
  libyaml-dev \
  libxml2-dev \
  libxslt1.1 \
  libxslt1-dev

# install ruby
RUN git clone https://github.com/sstephenson/ruby-build.git;\
  cd ruby-build;\
  sudo ./install.sh
RUN ruby-build 2.1.0 /usr/ruby

# install rubygems
RUN wget http://production.cf.rubygems.org/rubygems/rubygems-2.1.11.tgz;\
  tar xvzf rubygems-2.1.11.tgz;\
  cd rubygems-2.1.11;\
  ruby setup.rb

RUN gem install bundler
