require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MylistLogsController do

  # This should return the minimal set of attributes required to create a valid
  # MylistLog. As you add validations to MylistLog, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "mylist_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MylistLogsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mylist_logs as @mylist_logs" do
      mylist_log = MylistLog.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mylist_logs)).to eq([mylist_log])
    end
  end

  describe "GET show" do
    it "assigns the requested mylist_log as @mylist_log" do
      mylist_log = MylistLog.create! valid_attributes
      get :show, {:id => mylist_log.to_param}, valid_session
      expect(assigns(:mylist_log)).to eq(mylist_log)
    end
  end

  describe "GET new" do
    it "assigns a new mylist_log as @mylist_log" do
      get :new, {}, valid_session
      expect(assigns(:mylist_log)).to be_a_new(MylistLog)
    end
  end

  describe "GET edit" do
    it "assigns the requested mylist_log as @mylist_log" do
      mylist_log = MylistLog.create! valid_attributes
      get :edit, {:id => mylist_log.to_param}, valid_session
      expect(assigns(:mylist_log)).to eq(mylist_log)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MylistLog" do
        expect {
          post :create, {:mylist_log => valid_attributes}, valid_session
        }.to change(MylistLog, :count).by(1)
      end

      it "assigns a newly created mylist_log as @mylist_log" do
        post :create, {:mylist_log => valid_attributes}, valid_session
        expect(assigns(:mylist_log)).to be_a(MylistLog)
        expect(assigns(:mylist_log)).to be_persisted
      end

      it "redirects to the created mylist_log" do
        post :create, {:mylist_log => valid_attributes}, valid_session
        expect(response).to redirect_to(MylistLog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mylist_log as @mylist_log" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(MylistLog).to receive(:save).and_return(false)
        post :create, {:mylist_log => { "mylist_id" => "invalid value" }}, valid_session
        expect(assigns(:mylist_log)).to be_a_new(MylistLog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(MylistLog).to receive(:save).and_return(false)
        post :create, {:mylist_log => { "mylist_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mylist_log" do
        mylist_log = MylistLog.create! valid_attributes
        # Assuming there are no other mylist_logs in the database, this
        # specifies that the MylistLog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(MylistLog).to receive(:update).with({ "mylist_id" => "1" })
        put :update, {:id => mylist_log.to_param, :mylist_log => { "mylist_id" => "1" }}, valid_session
      end

      it "assigns the requested mylist_log as @mylist_log" do
        mylist_log = MylistLog.create! valid_attributes
        put :update, {:id => mylist_log.to_param, :mylist_log => valid_attributes}, valid_session
        expect(assigns(:mylist_log)).to eq(mylist_log)
      end

      it "redirects to the mylist_log" do
        mylist_log = MylistLog.create! valid_attributes
        put :update, {:id => mylist_log.to_param, :mylist_log => valid_attributes}, valid_session
        expect(response).to redirect_to(mylist_log)
      end
    end

    describe "with invalid params" do
      it "assigns the mylist_log as @mylist_log" do
        mylist_log = MylistLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(MylistLog).to receive(:save).and_return(false)
        put :update, {:id => mylist_log.to_param, :mylist_log => { "mylist_id" => "invalid value" }}, valid_session
        expect(assigns(:mylist_log)).to eq(mylist_log)
      end

      it "re-renders the 'edit' template" do
        mylist_log = MylistLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(MylistLog).to receive(:save).and_return(false)
        put :update, {:id => mylist_log.to_param, :mylist_log => { "mylist_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mylist_log" do
      mylist_log = MylistLog.create! valid_attributes
      expect {
        delete :destroy, {:id => mylist_log.to_param}, valid_session
      }.to change(MylistLog, :count).by(-1)
    end

    it "redirects to the mylist_logs list" do
      mylist_log = MylistLog.create! valid_attributes
      delete :destroy, {:id => mylist_log.to_param}, valid_session
      expect(response).to redirect_to(mylist_logs_url)
    end
  end

end
